[package]
name = "compress-mkv"
version = "0.6.0"
edition = "2024"

[dependencies]
human-repr = "1.1.0"
kdam = "0.6.2"
rustop = "1.1.4"
serde = { version = "1.0.219", features = [ "derive" ] }
serde_json = "1.0.140"
signal-hook = "0.3.17"
