[package]
name = "compress-mkv"
version = "0.7.0"
edition = "2024"

[dependencies]
humanize-bytes = "1.0.6"
ratatui = "0.29.0"
serde = { version = "1.0.219", features = [ "derive" ] }
serde_json = "1.0.140"
